### PR TITLE
Update bootstrap and make mobile-ready

### PR DESCRIPTION
**Pull request by jasonlally**
cc: @sfbrigade/website-tools-core-team 

This pull request isn't ready for merge yet, but I want to benefit from all your brilliant ideas and make sure I'm heading in the right direction. I checked in with @therebelrobot on this and he gave me some great feedback that I haven't implemented yet. 

## Purpose

After setting the application up locally and digging in I really wanted to make sure we start improving the mobile experience, which led me to a handful of changes bulleted below. I'm trying to keep the changes mostly foundational and not make any big design changes without feedback or input from others (and hopefully some user testing). This also addresses #52 

## What's been done

In order to make the foundational changes I started with some basic updates including

- Updating bootstrap from 2 to 3 (css and js)
- Updating jQuery to 1.9.1 (the minimum requirement to support bootstrap.js
- Updating jQuery .live calls to .on (live was deprecated in 1.7)
- Modified the underlying layout to use column classes (col-*-#) instead of table classes, making the interface less rigid
- Added some media queries so that the sidebar is absolutely positioned with overflow set to scroll on big screens and pops to the top on small (mobile) screens
- Have a basic link to toggle the menu on mobile to reveal the login

## What's left to do

Based on feedback, I'd like to at a minimum get the following done before the PR is worth merging:

- [x] Modify the sidebar on mobile into a collapsible menu with a hamburger menu icon to indicate it's collapsible (replacing the link that's there now and only showing the logo when it's collapsed)
- [x] Make the map disappear when the menu is toggled on mobile
- [x] Modify CSS to do a full height map instead of javascript. I know, that's terrible I did that! :smile: 

## For discussion

These aren't necessarily in the critical path for getting an initial workable mobile version done, but I think we ought to tackle these sooner rather than later. Here are some points of discussion:

1. Should we modify the number of points dropped and the zoom level when viewing on smaller screens? My hypothesis is that when on a smaller screen, you are more likely interested in what's immediately around you OR at a minimum it'll be less overwhelming to a user to drop them into that experience and then invite them through the interface to explore.

screen shot 2015-11-04 at 10 10 40 pm

2. Should we change the interaction for signing in? For both the mobile and desktop experience, it may be more useful to have 2 fields: email and password and 2 buttons "Sign In" + "Sign Up".  Clicking Sign up would reveal the additional fields similar to what it does now. Less cognitive overload and less stuff to load in the initial interface.

screen shot 2015-11-04 at 10 11 40 pm 1

3. Should we hook up the information window on the map where it says "Sign in to adopt this Drain" to the sign in/sign up form itself? I could imagine an interaction where a user clicks on that link and it pops them over to the form.

screen shot 2015-11-04 at 10 11 17 pm

I'm sure there are things I'm missing but that's it for now.

### CODE REVIEW

**Comment by jszwedko** [comment]
@jasonlally awesome work :trumpet:

For what it's worth, I'm perfectly happy to merge the changes you have now as it is still an improvement (assuming it doesn't need more work to continue functioning correctly) and then finish off the remaining work in subsequent pull requests. I've often seen feature creep stop pull requests from ever making it into master.

Per your discussion points:

> Should we modify the number of points dropped and the zoom level when viewing on smaller screens? My hypothesis is that when on a smaller screen, you are more likely interested in what's immediately around you OR at a minimum it'll be less overwhelming to a user to drop them into that experience and then invite them through the interface to explore.

We briefly discussed showing aggregate pins when zoomed out (see https://developers.google.com/maps/articles/toomanymarkers?hl=en), but, at the least, I think dropping them into the map zoomed in further so they can see the drains immediately around them makes sense.

> Should we change the interaction for signing in? For both the mobile and desktop experience, it may be more useful to have 2 fields: email and password and 2 buttons "Sign In" + "Sign Up". Clicking Sign up would reveal the additional fields similar to what it does now. Less cognitive overload and less stuff to load in the initial interface.

I've seen this approach used elsewhere and enjoyed it.

> Should we hook up the information window on the map where it says "Sign in to adopt this Drain" to the sign in/sign up form itself? I could imagine an interaction where a user clicks on that link and it pops them over to the form.

I think this makes sense.

For all of these discussion points, I definitely feel like they could be standalone pull requests or issues (replete with their own discussions) than trying to bundle up here.

**Comment by jszwedko** [comment]
Overall :shipit: on the diff so far -- I didn't try poking at it locally, but if we decide to merge this PR, I can do that.

**Comment by jasonlally** [comment]
I agree on not waiting on the discussion points for merge, these are likely additional issues maybe with their own PR's, but they were somewhat salient and top of head.

I would like to just wrap up the 3 to-do's, which shouldn't take long, as they're more functional/foundational.

**Comment by jasonlally** [comment]
I'll try to wrap the todos tonight. Also forgot to cc: @hackajesse

**Comment by jszwedko** [comment]
@jasonlally :+1: I missed the TODOs -- they seem completely reasonable.

**Comment by jasonlally** [comment]
I wrapped up the 3 todos above with the latest commits. Can someone take a look?

**Comment by afomi** [comment]
lgtm

**Comment by jszwedko** [comment]
@jasonlally nice work! It looks like the mobile behavior is a bit unexpected when logged in. I see something like:

2015-11-12-095018_314x527_scrot

Where the top part is scrollable (I can scroll up to the hamburger icon, but clicking it does nothing). The behavior when not logged in seems correct (the header shows at the top and you can click the hamburger icon to bring up the login screen).

Overall I like the approach though and it'll definitely be a better mobile experience than what we currently have.

**Comment by jasonlally** [comment]
Thanks! I'll investigate, I think I know what to do here. Shouldn't take long. I'll work on it tonight or this weekend.

**Comment by jasonlally** [comment]
@jszwedko I think i took care of the issue. In the process, I made a small choice to comment out the flash messages in main.js.erb for sign in and sign out. This makes the mobile interface a bit simpler. 

I also got rid of the tagline when logged in. My assumption being that we can save that space and folks that have signed up will have received a welcome email with the purpose so they don't need a reminder while logged in.

However, I can imagine incorporating those back in using less space and maybe putting them somewhere else in the interface on mobile.

screen shot 2015-11-15 at 8 05 42 pm

**Comment by jasonlally** [comment]
@sfbrigade/core-website-tools is this merge worthy?

**Comment by jszwedko** [comment]
:+1: :100: looks good now, thank you!

**Pull request merged**
