### PR TITLE
Some more changes for drain import

### PR DESCRIPTION
**Pull request by jszwedko**
Made some more changes on top of #198 (thanks so much for getting this rolling
@squidarth !):

* internationalizing the code a bit to make it more reusable by others (still
  needs some more work here to be completely reusable, but this is closer).
* adjusted so that, if a drain is adopted, it doesn't overwrite the name
* add a couple more test cases

### CODE REVIEW

**Comment by jszwedko** [comment]
I'm attempting to run this against the staging environment with a full copy of the production database currently, but it is taking a while for the initial queries. May need to circle back and tune this, but I'll let it run for now.

cc/ @jasonlally

**Comment by squidarth** [comment]
Thanks for making these updates @jszwedko! Good to know we should keep the nouns general (thing vs. drain), and that i18n needs to be taken into account

**Comment by jszwedko** [comment]
:+1: no worries, I neglected to suggest the changes when looking at your PR.

I ended up killing the import in the staging environment after letting it run for 30 minutes. I'm guessing it might need to be reworked a bit to work with the 20000 or so records. I'll dig in some more on Wednesday or, failing that, this upcoming weekend, but feel free to poke first if you have some time @squidarth.

**Comment by jasonlally** [comment]
@jszwedko - you want to try to check in on this tomorrow? I'd like to be more helpful on this than I've been able to.

**Comment by squidarth** [comment]
Sorry for being somewhat MIA on this! I can also take a look tomorrow or Thurs eve

**Comment by jszwedko** [comment]
Pushed a commit (https://github.com/sfbrigade/adopt-a-drain/pull/217/commits/f757031eb553cad24a87325187fb9ef8b3c35092) that reworked the logic to rely much more heavily on PostgresSQL to do the heavy lifting. Locally, it ran in about 30s, but I'll need to test how it performs in staging. I also want to refactor it a bit.

@jeanwalshie @jasonlally During testing I discovered that one of the IDs for the drain had a `-ERROR` suffixed to it. Do you know if this is expected and if we should just ignore these drains?

Only example:

```
156023,N-43083-ERROR,STORM,Storm; even if DS flow is combined,Catch Basin Drain,6006518.46,2117187.67,"(37.7937619281877, -122.421405934487)"
```

**Comment by chaunceygraves** [comment]
Not sure how the maximo ID got “-ERROR” appended to it, but made me realize we were not filtering out NON active statuses from our drain View for dataSF: I’ve added where clause for status = active so as not to send past, future or never-existed-in-the-first-place drains  (whoops! Funny how no one noticed?)

John Seagrave  | Engineering Associate
Hydraulic Engineering  |  Public Works  |  City and County of San Francisco
1680 Mission St |  San Francisco, CA 94103   |  (415) 554-8305 |  john.seagrave@sfdpw.org<mailto:john.seagrave@sfdpw.org>

**Comment by jszwedko** [comment]
Refactored in https://github.com/sfbrigade/adopt-a-drain/pull/217/commits/70fb3626482cf7877f7378216d996193510afcd9 -- rebased onto origin/production to resolve conflicts.

**Comment by jszwedko** [comment]
@chaunceygraves hmm, interesting, can you clarify more about what non active drains look like in the dataset? The one we are using is here: https://data.sfgov.org/City-Infrastructure/Stormwater-inlets-drains-and-catch-basins/jtgq-b7c5

@squidarth @jasonlally I think this code is ready for review if either of you get a moment.

**Comment by chaunceygraves** [comment]
Jesse: We never intended to send Non active drains to dataSF or adopt-a-drain, and they are no longer in view that Jeanine is pulling, so now is non issue.
thanks

John Seagrave  | Engineering Associate
Hydraulic Engineering  |  Public Works  |  City and County of San Francisco
1680 Mission St |  San Francisco, CA 94103   |  (415) 554-8305 |  john.seagrave@sfdpw.org<mailto:john.seagrave@sfdpw.org>

**Comment by jszwedko** [comment]
@changjieyang ah, I see! Thank you!

**Comment by jszwedko** [comment]
Had a chance to test this out in staging tonight; merging and will configure the scheduled task in the production app.

**Pull request merged**
