### PR TITLE
Show guidelines when logged in

### LINKED ISSUE #117: Show guidelines when logged in
The following is shown when the user is not logged in, but is not once they login. We should show the guidelines in both cases.

2016-01-13-211934_323x160_scrot

### PR DESCRIPTION
**Pull request by jszwedko**
Not sure why these were hidden, but it seems like a good idea to always
have the visible.

Fixes #117

### CODE REVIEW

**Comment by jasonlally** [comment]
Agree, I have to check this on mobile though before merging.

**Comment by jszwedko** [comment]
@jasonlally you were right, on mobile this takes up the search area so that you see something like:

2016-01-21-204226_414x661_scrot

@jeanwalshie @jasonlally how do you feel about moving it lower on the sidebar to alleviate this issue? Something like:

2016-01-21-204309_457x880_scrot

**Comment by jszwedko** [comment]
bump @jasonlally

**Comment by jszwedko** [comment]
@jasonlally pushed https://github.com/sfbrigade/adopt-a-drain/commit/bb773abdc01c907211ee81594ab63386d2a91bc3 which conditionally shows it below when on mobile. I.e. you get:

2016-01-29-195216_413x366_scrot

transitioning to

2016-01-29-195227_413x452_scrot

Let me know what you think!

**Comment by jasonlally** [comment]
:+1: merging

**Pull request merged**
