### PR TITLE
208/231 replace home image, rescale, add horz scaling to "My Drains"

### PR DESCRIPTION
**Pull request by jafowler49**
Pull Request for issue https://github.com/sfbrigade/adopt-a-drain/issues/208

I only replaced one image as the other one was barely visible... I attached a screenshot.

Thanks!
adopt1

### CODE REVIEW

**Comment by jeanwalshie** [comment]
hey @jafowler49 is that the public works logo i sent you? if so, it's the wrong one! sorry. the correct one looks like this: http://sfpublicworks.org/

blue square...

**Comment by chaunceygraves** [comment]
Attached is probably higher resolution than you need.

John Seagrave  | Engineering Associate
Hydraulic Engineering  |  Public Works  |  City and County of San Francisco
1680 Mission St |  San Francisco, CA 94103   |  (415) 554-8305 |  john.seagrave@sfdpw.org<mailto:john.seagrave@sfdpw.org>

**Comment by jafowler49** [comment]
Just added a new SFDPW jpg that John sent, and kept the old SF PUC logo. They aren't vector based, but they are high resolution so I think they scale ok.

**Comment by jszwedko** [comment]
:+1: :+1: this looks good.

**Pull request merged**
