### PR TITLE
Update safety message

### PR DESCRIPTION
**Pull request by ralam**
Update safety message in modal popup to match [revised text](https://docs.google.com/document/d/1PVGZ-B-etARxIyMxNx0yMjtcNywIrIZlFVk-RS35C3s/edit).

### CODE REVIEW

**Comment by jszwedko** [comment]
Oops! Hadn't seen this when I opened #132. It looks like you have some indentation issues (you can see the failures locally by running `./bin/rake`). Happy to close mine in lieu of this one.

**Comment by jszwedko** [comment]
`strong` is a better tag to be using here, I'll close mine.

**Comment by ralam** [comment]
Thanks for catching that! I've fixed the indentation issues.

**Comment by jszwedko** [comment]
:+1: looks good to me!

**Pull request merged**
