### PR TITLE
update gems, addDataSF Logo addresses #106

### PR DESCRIPTION
**Pull request by jasonlally**
@jszwedko - finally a logo, not awesome, but gets the job done for now.

### CODE REVIEW

**Comment by jszwedko** [comment]
Looks like your bundle update caused rubocop to start complaining about deprecated directives in `.rubocop.yml`, but otherwise :+1: :+1:

**Comment by jasonlally** [comment]
Should I fix that first before merging?

**Comment by jszwedko** [comment]
That'd be preferred :)

**Comment by jszwedko** [comment]
:+1: thank you!

**Pull request merged**
