### PR TITLE
Rename admin columns 224

### PR DESCRIPTION
**Pull request by jafowler49**

### CODE REVIEW

**Comment by jafowler49** [comment]
@jszwedko thanks for catching the updated_at/created_at mistakes

I rolled back that migration and added labels as you suggested. 

Fyi, I deleted the last pull request and created this one since I was receiving failed Travis CI builds. Turns out the issue was just a spacing issue in the script I edited.

Thanks!

**Comment by jszwedko** [comment]
:+1: looks good @jafowler49

**Comment by jafowler49** [comment]
@jszwedko @jeanwalshie Has this been integrated to the live site? If not, what are the Heroku credentials I would need in order to do that?

Also, how does someone become an Admin for the Adopt-a-Drain website from the front-end? I did it on my local system by changing the database field via the Postgres client.

Thanks

**Comment by jszwedko** [comment]
@jafowler49 this is live now. I can add you as a collaborator on Heroku as well as an admin in adopt-a-drain if you want to give me the e-mail you used for each (either here or via e-mail).

I'm also thinking we could change the branching structure and rely on TravisCI to make it more obvious what is deployed, i.e. with a `staging` branch that would automatically deploy to the staging server and we could re-purpose the `production` branch to deploy to production. I'll think on that a bit more.

**Comment by jafowler49** [comment]
thanks @jszwedko ... my email for both is jafowler49@yahoo.com

that build process you proposed sounds good

**Comment by jszwedko** [comment]
@jafowler49 apologies, just circling back to this now, but I've added you as an admin in adopt-a-drain and as a collaborator on the Heroku projects (the latter I used your @sfgov.org address for).

**Pull request merged**
