### PR TITLE
Move reset password form to the main site

### PR DESCRIPTION
**Pull request by jszwedko**
Instead of an unformatted landing page.

This causes the password reset action (Passwords#edit) to render the
main page, but show the reset form in the sidebar. It then posts
asynchronously to set the new password and sign in the user. If the
reset is successful, renders the search form.

Also update some of the language to make it clearer that it is sending
a password reset email rather than your password in clear text.

Addresses #93

### CODE REVIEW

**Comment by jszwedko** [comment]
@jasonlally this is ready for you to take a look at when you get a chance.

**Comment by jasonlally** [comment]
Much better :+1: 

Looks like CI is failing because of coverage, it only decreased by .8% can we just merge?

**Comment by jszwedko** [comment]
@jasonlally added another test case which actually exposed some redundant code and missing flash message.

**Comment by jasonlally** [comment]
Okay, great!

**Pull request merged**
