### PR TITLE
Load drains

### PR DESCRIPTION
**Pull request by afomi**

### CODE REVIEW

**Comment by jasonlally** [comment]
There seems to be an issue wiht using PUC_Maximo_Asset_ID. These IDs all start with N- and I believe the schema expects a numeric type.

Three options I see here:

1. Remove "N-" and load the remainder, if we need to present this to a PUC user we can just add N- to the Node ID in the report/interface, not sure if that's going to be necessary yet anyway
2. Flip back to DPW_Node_ID, similarly, we can crosswalk this later, but probably more work to crosswalk technically than to just present the ID and prepend N-
3. Modify schema to accept a string

**Comment by afomi** [comment]
1. Seems simple enough. Though, relies on a known-convention.
2. Also simple. Not sure what the use cases and reporting needs are here.
3. Least feasible.  Easy to do for this instance, but creates and awkward fork and a need to PR core with a significant change.

Another options is to add an `external_id` -like field that is a `string`, and PR that upstream, which I'd guess would be more feasible. We can ask @sferik.

**Comment by sferik** [comment]
@afomi I probably wouldn’t merge a patch to migrate `external_id` to a `string` type upstream but obviously feel free to make this change in this fork, if that’s the path of least resistance.

Generally speaking, I only merge patches upstream that add some value to Adopt-a-Hydrant in Boston because that’s their actual codebase. It’s not clear to me that making things more generic in this way would have any tangible benefit to the City of Boston and I can think of a couple disadvantages.

It’s best to think of Adopt-a-Hydrant Boston as a reference implementation, rather than a generic template.

**Comment by afomi** [comment]
Thanks for the prompt feedback @sferik! We'll proceed accordingly.

**Comment by jszwedko** [comment]
Seems like modifying the schema to use a `varchar` for this field is the best route, what do you think @afomi ?

**Comment by afomi** [comment]
ya, `varchar` seems simple. I'll try to knock this out this weekend.

**Comment by jasonlally** [comment]
I didn't do much here except to only load drains if they are either:

1. Storm Water Inlet Drain
2. Catch Basin Drain 

This is 98% of the drains, but keeps out the unadoptable ones. Also, I didn't do anything regarding the city_id.

**Comment by afomi** [comment]
The `N-` will now be removed. Will this load work, or does data need to be migrated?

**Comment by afomi** [comment]
21364 Drains loaded for adoptadrainsf.herokuapp.com

**Pull request merged**
