### PR TITLE
Add system use code to things

### LINKED ISSUE #100: Add storm_use_code to Things table and pass back to frontend
I think all that needs to happen is to:

- [ ] Add storm_use_code to schema on Things table
- [ ] Populate storm_use_code from drains data

The `find_closest` method on the thing model already passes back all fields, so once this is done, it should be pretty straightforward to swap in the other icon (which is already designed) when we match MS4 to the storm_use_code per the discussion on #38

### PR DESCRIPTION
**Pull request by jszwedko**
And populate via the data:load_drains rake task. Refactor the rake task to
update fields using the unique city_id identifier if the drain already
exists.

Require rake in the tasks file so that the environment is loaded properly.

Fixes #100

### CODE REVIEW

**Comment by jszwedko** [comment]
cc @jasonlally

I kept the field name from the CSV file (system_use_code), but let me know if you prefer storm_use_code.

Just give a :+1: if this looks good to you -- I'll merge and run the migration on the "production" site (the migration needs to be ran immediately after the deploy to avoid the site appearing to be offline).

**Comment by jasonlally** [comment]
:+1: Looks good - yes on system_use_code

**Comment by jszwedko** [comment]
:+1: I'll merge and walk out now

**Comment by jszwedko** [comment]
Migrated the existing dataset to back populate the field

**Pull request merged**
